spring:
  application:
    name: api-gateway
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: ms-usuarios
          uri: ${MS_USUARIOS_URL:http://localhost:8081}
          predicates:
            - Path=/usuarios/**, /auth/**

        - id: ms-lancamentos
          uri: ${MS_LANCAMENTOS_URL:http://localhost:8083}
          predicates:
            - Path=/lancamentos/**

        - id: ms-centro-custo
          uri: ${MS_CENTRO_CUSTO_URL:http://localhost:8082}
          predicates:
            - Path=/centros-custo/**

        - id: ms-fluxo-caixa
          uri: ${MS_FLUXO_CAIXA_URL:http://localhost:8084}
          predicates:
            - Path=/fluxo-caixa/**

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}